### ISSUE TITLE
Roadmap to tiny-dnn v1.0.0

### ISSUE THREAD

**Issue by nyanp** [tiny-dnn/tiny-dnn#286]
## v1.0.0alpha on 23 August, 2016
- [ ] Add model serialization API @nyanp
- [ ] Add protobuf parser for tensorflow @Wangyida 
- [ ] Fix compiler warnings and style issues @nyanp

## v1.0.0 on 15 September, 2016
- [ ] Bug Fix
    - [ ] Fix unit test 
        - [ ] unpooling layer @Wangyida 
        - [ ] deconv layer @Wangyida 
    - [ ] Fix max-pooling bug(#271) @nyanp
- [ ] Improve quantized op API @Wangyida 
- [ ] Add lstm/rnn (#210) @nyanp
- [ ] Improve backend API
    - [ ] Redesign tensor_t structure @edgarriba 
    - [ ] Refactor backend device API to enable user to select multiple devices/backends
    - [ ] GPU integration
        - [ ] fully-connected-layer / forward @edgarriba 
        - [ ] fully-connected-layer / backward @edgarriba 
        - [ ] convolutional-layer / backward @edgarriba 
- [ ] Update documentations @nyanp

STRETCH GOALS
- [ ] Improve design of official document
- [ ] Add IOS example
- [ ] Create official logo for tiny-dnn @bhack 
- [ ] Replace unit test with gtest or CATCH @nyanp
- [ ] Multiple GPU support @edgarriba 
- [ ] Add benchmarking @nyanp
- [ ] Windows support for 3rd-party libraries
    - [ ] NNPACK @nyanp
    - [ ] gemmlowp @nyanp
    - [ ] libDNN @nyanp

**Comment by bhack** [comment]
Today it is the Alpha milestone day. What is the status of https://github.com/tiny-dnn/tiny-dnn/pull/254? What is the impact of quantizzation on @nyanp serializzation?

**Comment by bhack** [comment]
How many instructions we can cover on the internal avx backend using http://p12tic.github.io/libsimdpp/v2.0~rc2/libsimdpp/? So that we can have a defualt/fallback internal implentation also on ARM.

**Comment by nyanp** [comment]
@bhack  /cc: @edgarriba 
In v1.0.0alpha, serialization for quantized layer isn't supported. So no confliction between serialization and @Wangyida 's work.
Yes today is milestone day, but I hadn't enough time to complete #291... so I want to move release date to 8/30.

**Comment by Wangyida** [comment]
@bhack As suggested, I moved basic parser to io folder and make the parser example a standalone one in the examples/tensorflor_converter folder. This is complete in the parser stage.

**Comment by beru** [comment]
@bhack Thank you for the infomation, I didn't know about the library ( libsimdpp )
Relying on it would probablly ease maintanance cost when it comes to support multiple architectures.
But for performance wise, I wonder if this kind of “greatest common factor approach” is desirable.

**Comment by bhack** [comment]
This obiviousily can speed up the coverage on ARM/Neon but we need to have an inventory list cause this common istructions generally cover at max cases of when an istruction could be composed by a composition of istruction if are not directly covered. As example you can see https://github.com/p12tic/libsimdpp/issues/34#issuecomment-212538017

**Comment by nyanp** [comment]
@beru @bhack 
> I wonder if this kind of “greatest common factor” approach is desirable.

I think so, too.

> This obiviousily can speed up the coverage on ARM/Neon

It might not be so obvious... Sometimes optimizing compiler with straightforward code beats such "generic simd optimization" approach because a compiler knows much more about its target hardware (i.e. register size). I prefer to use hand-tuned one because deep learning on mobile platform is performance critical.

**Comment by bhack** [comment]
I think that can speedup in coverage if we have quite translable instructions. I'm also preferring hand-tuned neon kernel but this require some Neon specialists. So we are in a situation where on ARM we have only optimized quantized kernels (that probably on mobile makes sense) trough gemmlowp for gemm.

**Comment by bhack** [comment]
This is the list of quantized kernels in TF: https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/quantization/kernels

**Comment by bhack** [comment]
Today it is 8/30. Do we want to move the release date to another target?

**Comment by nyanp** [comment]
@bhack /cc @edgarriba @Wangyida 
I hate to say this, but we need to move. I hadn't enough time to complete serialization task, and I think convolution bug should be solved before the alpha release. Let me move the release date to 9/12.

**Comment by bhack** [comment]
OK but I'm worried by memory handing bugs that users are reporting.

**Comment by nyanp** [comment]
@bhack 
Yes, they're critical issues we must solve before the alpha release. #298 would solve a part of them, and I'll check now.

**Comment by bhack** [comment]
Do we want to reschedule?

**Comment by VanushVaswani** [comment]
Why no GPU support?

**Comment by edgarriba** [comment]
@VanushVaswani Currently we just support convolution operation via OpenCL and LibDNN. However, we need to refactor the tensor structure to proper share memory pointers between devices in order to fully support nested operations and/or complex architectures.

**Comment by nyanp** [comment]
@edgarriba @Wangyida 
I think we need to reschedule, (and/or) shrink the scope of v1.0.0. When will be convenient for you to release v1.0.0?

**Comment by mordecaihamo** [comment]
@nyanp GR8 work. Could you point me to a semantic segmentation example. I could not find an example that is doing semantic segmentation using tiny dnn.
10x
